[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin=lib/openzeppelin-contracts/contracts/']
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200

[profile.test]
src = 'test'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin=lib/openzeppelin-contracts/contracts/']
